### ISSUE TITLE
Unable to install this plugin through phonegap build

### ISSUE THREAD

**Issue by Tawsif** [TomByrne/cordova-screenppi-plugin#1]
I am developing an application in cordova/phonegap with DevExtreme. I am adding plugins in my application via Online Phonegap Build. But when I am using this plugin : gap:plugin name="org.tbyrne.cordova.plugins.screenppi" version="1.3.0"   Error pop ups: Unsupported Plugin !!
If it is unsupported in that , how can I add in my application to access device ppi ? (I can't use CLI) @mbppower , or anyone please help me out. Thanks a lot in advance.

**Comment by TomByrne** [comment]
To use cordova plugins in Phonegap Build, the plugins must be approved by their team.
If there is a commercial requirement for this please contact me directly, otherwise, I'm afraid I can't submit this plugin to Phonegap at the moment.
